In [1]:
pip install xarray cfgrib pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xarray in /home/valau/.local/lib/python3.11/site-packages (2025.1.2)
Requirement already satisfied: cfgrib in /home/valau/.local/lib/python3.11/site-packages (0.9.15.0)
Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.24 in /opt/conda/lib/python3.11/site-packages (from xarray) (1.26.4)
Requirement already satisfied: packaging>=23.2 in /opt/conda/lib/python3.11/site-packages (from xarray) (24.0)
Requirement already satisfied: attrs>=19.2 in /opt/conda/lib/python3.11/site-packages (from cfgrib) (23.2.0)
Requirement already satisfied: click in /opt/conda/lib/python3.11/site-packages (from cfgrib) (8.1.7)
Requirement already satisfied: eccodes>=0.9.8 in /home/valau/.local/lib/python3.11/site-packages (from cfgrib) (2.41.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas) (2024.1)
Requirement already satisfied: cffi in /opt/conda/lib/python3.11/site-packages (from eccodes>=0.9.8->cfgrib) (1.16.0)
Requirement already satisfied: findlibs in /home/valau/.local/lib/python3.11/site-packages (from eccodes>=0.9.8->cfgrib) (0.1.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.11/site-packages (from cffi->eccodes>=0.9.8->cfgrib) (2.22)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import xarray as xr

In [3]:
# Replace 'your_file.grib' with the actual path to your GRIB file
file_path = 'Dataset/evap_total_cloud_2005-2024.grib'

try:
    ds = xr.open_dataset(file_path, engine='cfgrib')
    print(ds)
except ValueError as e:
    print(f"Error opening the GRIB file with cfgrib: {e}")

skipping variable: paramId==182 shortName='e'
Traceback (most recent call last):
  File "/home/valau/.local/lib/python3.11/site-packages/cfgrib/dataset.py", line 725, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/home/valau/.local/lib/python3.11/site-packages/cfgrib/dataset.py", line 641, in dict_merge
    raise DatasetBuildError(
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='time' value=Variable(dimensions=('time',), data=array([1104537600, 1104559200, 1104580800, ..., 1735624800, 1735646400,
       1735668000])) new_value=Variable(dimensions=('time',), data=array([1104516000, 1104559200, 1104602400, ..., 1735538400, 1735581600,
       1735624800]))

<xarray.Dataset> Size: 484MB
Dimensions:     (time: 29220, latitude: 41, longitude: 101)
Coordinates:
    number      int64 8B ...
  * time        (time) datetime64[ns] 234kB 2005-01-01 ... 2024-12-31T18:00:00
    step        timedelta64[ns] 8B ...
    surface     float64 8B ...
  * latitude    (latitude) float64 328B 35.0 34.75 34.5 ... 25.5 25.25 25.0
  * longitude   (longitude) float64 808B -100.0 -99.75 -99.5 ... -75.25 -75.0
    valid_time  (time) datetime64[ns] 234kB ...
Data variables:
    tcc         (time, latitude, longitude) float32 484MB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2025-06-02T22:46 GRIB to CDM+CF via cfgrib-0.9.1...

/home/valau/.local/lib/python3.11/site-packages/cfgrib/xarray_plugin.py:131: FutureWarning: In a future version of xarray decode_timedelta will default to False rather than None. To silence this warning, set decode_timedelta to True, False, or a 'CFTimedeltaCoder' instance.
  vars, attrs, coord_names = xr.conventions.decode_cf_variables(

In [4]:
indices = ['time', 'latitude', 'longitude']
data_vars = list(ds.keys())
relevant_vars = indices + data_vars
relevant_vars

['time', 'latitude', 'longitude', 'tcc']

In [5]:
#ds.groupby(coordinates).mean(dim='x')

In [6]:
df = ds[relevant_vars].to_dataframe().reset_index()[relevant_vars]

In [7]:
df.head()

        time  latitude  longitude       tcc
0 2005-01-01      35.0    -100.00  0.929993
1 2005-01-01      35.0     -99.75  0.945007
2 2005-01-01      35.0     -99.50  0.950012
3 2005-01-01      35.0     -99.25  0.947937
4 2005-01-01      35.0     -99.00  0.940430

In [8]:
df.shape

(121000020, 4)

In [9]:
indices = ['date', 'latitude', 'longitude']
df['date'] = df['time'].dt.date
df.drop(columns=['time'], inplace=True)
df.head()#['hour'] = df

   latitude  longitude       tcc        date
0      35.0    -100.00  0.929993  2005-01-01
1      35.0     -99.75  0.945007  2005-01-01
2      35.0     -99.50  0.950012  2005-01-01
3      35.0     -99.25  0.947937  2005-01-01
4      35.0     -99.00  0.940430  2005-01-01

In [ ]:
df.groupby(coordinates, sort=False)[data_variables].mean().reset_index()

In [ ]:
# Specify the file path
filepath = 'path/to/your/file.csv'

# Export DataFrame to CSV
df.to_csv(filepath, index=False)

In [ ]:
#for x in ds.keys():
#    print(x)
#ds['tcc']

In [ ]:
#df['time'][15475].date()#.head()

In [ ]:
#df['time'][15598].hour

In [ ]:
#df['time'][:20].dt.date[0]